-- =============================================================================
-- BOSAI Agent Memory Control Plane — Schema 001 Initial Setup
-- Milestone: BOSAI_COCKROACHDB_AWS_0E
-- Database:  bosai_agent_memory
-- Cluster:   bosai-memory-hack (AWS eu-central-1, CockroachDB v26.2.5)
--
-- Apply in CockroachDB Cloud SQL Shell against bosai_agent_memory.
-- Idempotent: uses CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Table 1: missions
-- Represents an active or historical incident/mission being governed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS missions (
    mission_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_key    STRING        NOT NULL,
    status          STRING        NOT NULL DEFAULT 'OPEN',
    observed_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    context_json    JSONB         NOT NULL DEFAULT '{}',

    CONSTRAINT chk_missions_status CHECK (status IN ('OPEN', 'CLOSED', 'ESCALATED'))
);

CREATE INDEX IF NOT EXISTS idx_missions_incident_key ON missions (incident_key);
CREATE INDEX IF NOT EXISTS idx_missions_status       ON missions (status);

-- ---------------------------------------------------------------------------
-- Table 2: memory_events
-- Stores operational memory with a 3-dimensional similarity vector.
-- Dimensions: [latency_pressure, error_pressure, dependency_risk_pressure]
-- All values normalised to [0.0, 1.0].
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS memory_events (
    memory_event_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mission_id        UUID          NOT NULL REFERENCES missions (mission_id) ON DELETE CASCADE,
    event_type        STRING        NOT NULL,
    content           STRING        NOT NULL,
    operational_vector VECTOR(3)   NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT chk_memory_event_type CHECK (
        event_type IN ('INCIDENT', 'RECOVERY', 'DEGRADATION', 'OBSERVATION', 'SYNTHETIC')
    )
);

CREATE INDEX IF NOT EXISTS idx_memory_events_mission_id ON memory_events (mission_id);

-- Vector index for cosine-similarity nearest-neighbour retrieval.
-- Uses CockroachDB native vector index (partition-tree, NOT pgvector IVF).
-- Valid storage parameters: min_partition_size, max_partition_size, build_beam_size.
-- The `lists` parameter belongs to pgvector/pg_ivfflat and is NOT supported here.
-- IF NOT EXISTS is NOT supported by CREATE VECTOR INDEX in CockroachDB v26.2.x;
-- the index is created unconditionally (safe because 001_init.sql is applied once).
CREATE VECTOR INDEX idx_memory_events_op_vector
    ON memory_events (operational_vector);

-- ---------------------------------------------------------------------------
-- Table 3: proposals
-- Records exact proposed state transitions generated by the agent.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposals (
    proposal_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mission_id   UUID        NOT NULL REFERENCES missions (mission_id) ON DELETE CASCADE,
    action_type  STRING      NOT NULL,
    target       STRING      NOT NULL,
    from_state   STRING      NOT NULL,
    to_state     STRING      NOT NULL,
    rationale    STRING      NOT NULL DEFAULT '',
    status       STRING      NOT NULL DEFAULT 'PENDING',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_proposals_status CHECK (
        status IN ('PENDING', 'APPROVED', 'DENIED', 'EXECUTED', 'EXPIRED')
    )
);

CREATE INDEX IF NOT EXISTS idx_proposals_mission_id ON proposals (mission_id);
CREATE INDEX IF NOT EXISTS idx_proposals_status     ON proposals (status);

-- ---------------------------------------------------------------------------
-- Table 4: approval_permits
-- Single-use, scoped, expiry-aware human GO permits.
-- consumed_at is set atomically when the permit is consumed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS approval_permits (
    permit_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mission_id   UUID        NOT NULL REFERENCES missions (mission_id) ON DELETE CASCADE,
    proposal_id  UUID        NOT NULL REFERENCES proposals (proposal_id) ON DELETE CASCADE,
    scope_hash   STRING      NOT NULL,
    issued_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ          DEFAULT NULL,
    status       STRING      NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT chk_permit_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED'))
);

CREATE INDEX IF NOT EXISTS idx_permits_mission_id  ON approval_permits (mission_id);
CREATE INDEX IF NOT EXISTS idx_permits_proposal_id ON approval_permits (proposal_id);
CREATE INDEX IF NOT EXISTS idx_permits_status      ON approval_permits (status);

-- ---------------------------------------------------------------------------
-- Table 5: service_state
-- Authoritative state record for each governed service.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_state (
    service_id  STRING      PRIMARY KEY,
    mode        STRING      NOT NULL DEFAULT 'NORMAL',
    version     INT8        NOT NULL DEFAULT 1,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_service_mode CHECK (mode IN ('NORMAL', 'SAFE', 'DEGRADED', 'MAINTENANCE'))
);

-- ---------------------------------------------------------------------------
-- Table 6: execution_receipts
-- Immutable audit log — records BOTH denied and executed outcomes.
-- permit_id is nullable (denials before permit issuance have no permit).
-- evidence_key is nullable (populated after S3 upload in 0F).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution_receipts (
    receipt_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mission_id      UUID        NOT NULL REFERENCES missions (mission_id) ON DELETE CASCADE,
    proposal_id     UUID        NOT NULL REFERENCES proposals (proposal_id) ON DELETE CASCADE,
    permit_id       UUID                 DEFAULT NULL REFERENCES approval_permits (permit_id) ON DELETE SET NULL,
    outcome         STRING      NOT NULL,
    expected_state  STRING      NOT NULL,
    observed_state  STRING      NOT NULL,
    reason          STRING      NOT NULL DEFAULT '',
    evidence_key    STRING               DEFAULT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_receipt_outcome CHECK (
        outcome IN (
            'EXECUTED',
            'DENIED_NO_PERMIT',
            'DENIED_EXPIRED_PERMIT',
            'DENIED_REPLAYED_PERMIT',
            'DENIED_SCOPE_MISMATCH',
            'DENIED_MISSION_MISMATCH',
            'DENIED_STATE_MISMATCH',
            'DENIED_POLICY',
            'READBACK_MISMATCH'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_receipts_mission_id  ON execution_receipts (mission_id);
CREATE INDEX IF NOT EXISTS idx_receipts_proposal_id ON execution_receipts (proposal_id);
CREATE INDEX IF NOT EXISTS idx_receipts_outcome     ON execution_receipts (outcome);
